# coverage campaign entry
# rule_key: guardian.rapidapi-access-token
IzcMrITtrxqLuIPJFUraCD53PwoxLKMbG8dHMWDJu9s8S4FvfKrapidapir9CD860uc3HtLLe1L
, =	madd7dk7o0mbe38m8-johwdwxxfbx1ndptt_e00rg028y8e3l_\r
